services:

  # docker run command:
  # docker run -i -d --rm --name=pragmatic.programmer.tips.email.service --mount type=bind,source=C:/Users/null/source/repos/pragmatic.programmer.tips/.docker.files/email.service.logs,target=/bin/pragmatic.programmer.tips/logs -e ENVIRONMENT=dev chrwalte/pragmatic.programmer.tips.service:latest

  pragmatic.programmer.tips.email.service:
    container_name: pragmatic.programmer.tips.email.service
    hostname: pragmatic.programmer.tips.email.service
    image: chrwalte/pragmatic.programmer.tips.service:build
    environment:
      # ENVIRONMENT: "prod"
      ENVIRONMENT: "dev"
    volumes:
      - ".docker-compose.files/email.service.logs/:/bin/pragmatic.programmer.tips/logs/"
      - ".docker-compose.files/data/:/bin/pragmatic.programmer.tips/data/raw/"
      - "./pragmatic.programmer.tips.service/configuration.json:/bin/pragmatic.programmer.tips/configuration.json"
      # ENVIRONMENT CONFIGURATION:
      # - "./pragmatic.programmer.tips.service/configuration.dev.json:/bin/pragmatic.programmer.tips/configuration.dev.json"
      # - "./pragmatic.programmer.tips.service/configuration.prod.json:/bin/pragmatic.programmer.tips/configuration.prod.json"
    networks:
      - pragmatic.programmer.tips.email.service.network
    restart: unless-stopped

  # docker run command:
  # docker run -i -d --rm --name=pragmatic.programmer.tips.web.api -p 30011:80 --mount type=bind,source=C:/Users/null/source/repos/pragmatic.programmer.tips/.docker.files/api.logs,target=/bin/pragmatic.programmer.tips/logs --mount type=bind,source=C:/Users/null/source/repos/pragmatic.programmer.tips/.docker-compose.files/data,target=/bin/pragmatic.programmer.tips/data/raw -e ASPNETCORE_ENVIRONMENT=dev chrwalte/pragmatic.programmer.tips.api:latest

  pragmatic.programmer.tips.web.api:
    container_name: pragmatic.programmer.tips.web.api
    hostname: pragmatic.programmer.tips.web.api
    image: chrwalte/pragmatic.programmer.tips.api:build
    ports:
      - 30011:80
    environment:
      # ASPNETCORE_ENVIRONMENT: "prod"
      ASPNETCORE_ENVIRONMENT: "dev"
    volumes:
      - ".docker-compose.files/api.logs/:/bin/pragmatic.programmer.tips/logs/"
      - ".docker-compose.files/data/:/bin/pragmatic.programmer.tips/data/raw/"
      # ENVIRONMENT CONFIGURATION:
      # - "./pragmatic.programmer.tips.api/appsettings.dev.json:/bin/pragmatic.programmer.tips/appsettings.dev.json"
      # - "./pragmatic.programmer.tips.api/appsettings.prod.json:/bin/pragmatic.programmer.tips/appsettings.prod.json"
    networks:
      - pragmatic.programmer.tips.web.network
    restart: unless-stopped

  # docker run command:
  # docker run -i -d --rm --name=pragmatic.programmer.tips.web.client -p 30010:80 -e ENVIRONMENT=dev chrwalte/pragmatic.programmer.tips.client:latest

  pragmatic.programmer.tips.web.client:
    container_name: pragmatic.programmer.tips.web.client
    hostname: pragmatic.programmer.tips.web.client
    image: chrwalte/pragmatic.programmer.tips.client:build
    ports:
      - 30010:80
    environment:
      # ENVIRONMENT: "prod"
      ENVIRONMENT: "dev"
    networks:
      - pragmatic.programmer.tips.web.network
    restart: unless-stopped

networks:

  pragmatic.programmer.tips.email.service.network:
    name: pragmatic.programmer.tips.email.service.network

  pragmatic.programmer.tips.web.network:
    name: pragmatic.programmer.tips.web.network
